### ISSUE TITLE
./gradlew test does not execute groovy tests

### ISSUE THREAD

**Issue by frangarcia** [micronaut-guides/creating-your-first-micronaut-app-groovy#4]
I am following the tutorial at https://guides.micronaut.io/creating-your-first-micronaut-app-groovy/guide/index.html and running the gradle command ./gradlew test does not run the spock specifications. Weirdly, it does it when I run it from IntelliJ.

The blaming part is

```
// use JUnit 5 platform
test {
    useJUnitPlatform()
}
```
in build.gradle file. Commenting out this part makes the trick.

**Comment by ilopmar** [comment]
Thank you. I've fixed the issue: https://github.com/micronaut-guides/creating-your-first-micronaut-app-groovy/commit/bd899cdc7933fc5017e5776cb7d5aad06b21e5d8

**Comment by andersaaberg** [comment]
I had the same issue when using the command: `mn create-app example.micronaut.complete --features=groovy` but not when using the command `mn create-app example.micronaut.complete --lang=groovy`

I think that the latter command should be used in the guide instead of the first one: https://guides.micronaut.io/creating-your-first-micronaut-app-groovy/guide/index.html
